export declare const PREFIX_CLS = "webreactui";
export declare const PREFIX_CLS_MODAL: string;
export declare const PREFIX_CLS_INPUT: string;
export declare const PREFIX_CLS_TEXTAREA: string;
export declare const PREFIX_CLS_COLOR_PICKER: string;
export declare const PREFIX_CLS_BUTTON: string;
export declare const PREFIX_CLS_MESSAGE: string;
export declare const PREFIX_CLS_DESCRIPTIONS: string;
export declare const PREFIX_CLS_MEMBER_SELECT: string;
export declare const PREFIX_CLS_UPLOAD: string;
export declare const PREFIX_CLS_MAP_SELECT: string;
export declare const PREFIX_CLS_SEARCH_BAR: string;
export declare const PREFIX_CLS_NOTIFICATION: string;
export declare const PREFIX_CLS_UPLOADVIDEO: string;
export declare const PREFIX_CLS_ELLIPSIS: string;
export declare const IMAGE_UPLOAD_TOKEN = "/p/wedding/home/APIUtils/image_upload_token";
export declare const VIDEO_UPLOAD_TOKEN = "/p/wedding/home/APIUtils/video_upload_token";
export declare const ALL_UPLOAD_TOKEN = "/p/wedding/Home/APIUtils/all_upload_token";
